---
- hosts: windows # group 
  vars_files:
      - vars.yml

  tasks:

  # --extra-vars "username=<user> usergroup=<group>"
  - name: Ensure user bob is present
    win_user:
      name: {{ username  }}
      password: {{ password  }}
      state: present
      groups:
        - {{ usergroup }}
