---
- hosts: windows # group 
  vars_files:
      - vars.yml

  tasks:

  # --extra-vars "username=<user> usergroup=<group> fullname=<fullname> description=<description>"
  - name: Create new user 
    win_user:
      name: {{ username  }}
      password: {{ password  }}
      state: present
      description: {{ description }}
      fullname: {{ fullname }}
      password_expired : yes # This will force user to reset password on next login
      groups:
        - {{ usergroup }}
