---
- hosts: windows # group 
  become: true
  vars_files:
      - vars.yml

  tasks:

  # --extra-vars "username=<user>"
  - name: Disable user account
    win_user:
      name: {{ username }}
      account_disabled : true
