---
- hosts: linux # group 
  become: true
  vars_files:
      - vars.yml

  tasks:
  - name: generate password for new user(same as username)
    shell:  mkpasswd --method=SHA-512 {{username}}
    register: user_pw

  - name: Create addtional user(updates password if password differs)
    user:
      name:  "{{ username }}"
      group: "{{ usergroup }}"
      password: "{{ user_pw.stdout }}"
      update_password: on_create
      state: present
    register: user_state

  - name: Force user to reset password at first login(only if a new user is created)
    shell: passwd --expire {{ username }}
    when: user_state.changed