---
- hosts: linux
  become: true
  vars_files:
      - vars.yml

  tasks:
  - name: Remove users
    user:
      name: "{{ item.name }}"
      state: absent
      remove: yes
    with_items: "{{ user_details }}"