---
- hosts: linux
  become: true
  vars_files:
      - vars.yml
  roles:
    - ../roles/user_exists

  tasks:
  # - name: generate password for new user(same as username)
  #   shell:  mkpasswd --method=SHA-512 {{username}}
  #   register: user_pw
  - name: Delete old credential file
    file:
      path: "{{playbook_dir}}/credentials/{{username}}/password.txt"
      state: absent

  - name: Update user password to default
    user:
      name:  "{{ username }}"
      # password: "{{ user_pw.stdout }}"
      password: "{{ lookup('password', 'credentials/' + username + '/password.txt encrypt=sha512_crypt chars=ascii_letters,digits,hexdigits length=10') }}"

  - debug: 
      msg: "New Password is {{item.split()[0]}}"
    with_file:
      - "credentials/{{username}}/password.txt"

  # - name: setting the password without comments
  #   set_fact: 
  #     generated_password: "{{item.split()[0]}}"
  #   with_file:
  #     - "credentials/{{username}}/password.txt"

  # - name: Sending an e-mail using Gmail SMTP servers
  #   mail:
  #     to: om_paliwal@mentor.com
  #     subject: "Ansible-report: A new user added "
  #     body: 
  #       - User {{username}} on {{ ansible_hostname }} has been successfully provisioned.
  #       - Password is {{generated_password}}
  #   delegate_to: localhost