---
- hosts: linux
  become: true
  vars_files:
      - vars.yml

  tasks:
  - name: Check if user exists
    shell: egrep "^{{ username }}:" /etc/passwd

  - name: generate password for new user(same as username)
    shell:  mkpasswd --method=SHA-512 {{username}}
    register: user_pw
  
  - name: Update user password to default
    user:
      name:  "{{ username }}"
      password: "{{ user_pw.stdout }}"