---
- hosts: linux
  become: true
  vars_files:
      - vars.yml

  tasks:
  - name: Set password age to 180 days
    shell: chage -M 180 "{{ item.name }}"
    with_items: "{{ user_details }}"

  - name: Set password changed date
    shell: chage -d "July 23, 2020"  "{{ item.name }}"
    with_items: "{{ user_details }}"