---
- hosts: linux
  become: true
  vars_files:
      - vars.yml

  tasks:
  - name:
    raw: "chage -l user1 |grep -C 0 Account"
    register: expiry_old

  - name:
    raw: date +"%b %d, %Y"
    register: date_now

  - debug: var=date_now.stdout
  
  - name: Update user last password change dates
    shell: chage -d "Aug 27, 2020"   {{ username }}
  
  - name:
    raw: "chage -l user1 |grep -C 0 Account"
    register: expiry_new


  - debug:
      msg: "Old last password change: {{ expiry_old.stdout }}, New last password change: {{ expiry_new.stdout }}"
