---
- hosts: linux
  become: true
  vars_files:
      - vars.yml
  roles:
    - user_exists
    
  tasks:
  - name: Update user comment/label
    user:
      name:  "{{ username }}"
      comment: "{{ new_label }}"