---
- hosts: linux
  become: true
  vars_files:
      - vars.yml

  tasks:
  - name: Get current passwd expiry
    shell: chage -l {{ username }} |grep -C 0 'Last password change'"
    register: expiry_old

  - name:
    shell: date +"%b %d, %Y"
    register: date_now

  - debug: var=date_now.stdout
  
  - name: Update user last password change dates
    shell: chage -d "{{date_now.stdout}}"  {{ username }}
  
  - name:
    shell: "chage -l {{username}} |grep  -C 0 'Last password change'"
    register: expiry_new


  - debug:
      msg: 
      - "Old Password Expiry was {{ expiry_old.stdout.split(':')[1] }}"
      - "New Password Expiry is  {{ expiry_new.stdout.split(':')[1] }}"